development:
  adapter: mysql
  encoding: utf8
  database: jadesign_development
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  database: jadesign_test
  username: root
  password:

production:
  development
